name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  battery_info: ^1.1.1
  webview_flutter: ^3.0.4
  webview_windows: ^0.2.0

  flutter_vlc_player: ^7.4.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
